### ISSUE TITLE
BitScreen Settings

### ISSUE THREAD

**Issue by H34D** [Murmuration-Labs/bitscreen-client#2]
- [ ] Settings / BitScreen Toggle #1
- [ ] Settings / Toggle Local vs Remote Filter lists #3
- [ ] Settings / Share filter lists toggle #4
- [ ] Settings / Configure advanced filtering / validation services #5
