### ISSUE TITLE
BitScreen Filters

### ISSUE THREAD

**Issue by H34D** [Murmuration-Labs/bitscreen-client#6]
- [x] Filters / Make CID search work #7
- [x] Filters / Persist configured filters so that the BitScreen Plugin can read them #8
- [x] Filters / Change filter lists #9
